# Generated by Django 5.2.9 on 2025-12-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_message_deleted_by_message_deleted_for_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=255)),
                ('local', models.CharField(max_length=100)),
                ('data_evento', models.DateTimeField()),
            ],
        ),
    ]
