# Generated by ChatGPT
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_postlikeevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('descricao', models.TextField()),
                ('modalidade', models.CharField(max_length=60)),
                ('nivel_dificuldade', models.CharField(blank=True, max_length=60)),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('local', models.CharField(max_length=120)),
                ('distancia', models.CharField(blank=True, max_length=40)),
                ('max_participantes', models.PositiveIntegerField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='usuarios.usuario')),
            ],
            options={
                'ordering': ['-data', '-hora', '-criado_em'],
            },
        ),
    ]
