# Generated by ChatGPT
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='imagem_capa',
            field=models.ImageField(blank=True, upload_to='eventos/capa/'),
        ),
        migrations.AddField(
            model_name='evento',
            name='imagem_detalhe_1',
            field=models.ImageField(blank=True, upload_to='eventos/detalhes/'),
        ),
        migrations.AddField(
            model_name='evento',
            name='imagem_detalhe_2',
            field=models.ImageField(blank=True, upload_to='eventos/detalhes/'),
        ),
        migrations.AddField(
            model_name='evento',
            name='imagem_detalhe_3',
            field=models.ImageField(blank=True, upload_to='eventos/detalhes/'),
        ),
    ]
