# Generated by Django 5.1.3 on 2025-12-03 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_evento_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorited_eventos', to='usuarios.usuario'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
