# Generated by Django 5.2.8 on 2025-12-04 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_usuario_gm_permission_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('empresa', 'Empresa'), ('profissional', 'Profissional')], default='empresa', max_length=20)),
                ('nome_empresa', models.CharField(max_length=150)),
                ('cnpj', models.CharField(blank=True, max_length=20)),
                ('responsavel', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('endereco', models.CharField(blank=True, max_length=200)),
                ('area_atuacao', models.CharField(blank=True, max_length=150)),
                ('publico_alvo', models.CharField(blank=True, max_length=150)),
                ('rede_social', models.CharField(blank=True, max_length=150)),
                ('descricao', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='empresas/logos/')),
                ('professional_avatar', models.ImageField(blank=True, null=True, upload_to='empresas/profissionais/')),
                ('esportes', models.CharField(blank=True, max_length=200)),
                ('nivel', models.CharField(blank=True, max_length=60)),
                ('posicao', models.CharField(blank=True, max_length=120)),
                ('registro', models.CharField(blank=True, max_length=120)),
                ('portal_password', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empresa_profile', to='usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='EmpresaAnuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160)),
                ('categoria', models.CharField(max_length=60)),
                ('descricao', models.TextField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='empresas/anuncios/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anuncios', to='usuarios.empresaprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
