# Generated by Django 5.2.8 on 2025-12-04 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_empresaprofile_empresaanuncio'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresaprofile',
            name='gm_permission_level',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
